### ISSUE TITLE
f strings

### ISSUE THREAD

**Issue by ecoppen** [AnasHowlader/Programming-Challenges#1]
https://github.com/AnasHowlader/Programming-Challenges/blob/49043516a5587a40e6e20162bdee71ae172f9c09/Brampton%20Manor%20Academy/Programming%20Challenge%201.py#L23-L27

f strings will make printing differing data types together much easier.
`meters = f"Meters: {rods_to_meters(rodnum))}"`
f indicates you're going to include a variable or function return, {} is the variable or function call that you want to include.

**Comment by AnasHowlader** [comment]
Sir how do I post my updated version to github? also i cannot access my
code or edit it so i have to copy it as it is then do changes

**Comment by ecoppen** [comment]
If you upload a new version of the code, it will archive the old version and put the new one in its place. Alternatively you can install git, or use an IDE, or https://desktop.github.com/ to commit a change, then push it to the online repo.
