### ISSUE TITLE
Efficiency

### ISSUE THREAD

**Issue by ecoppen** [AnasHowlader/Programming-Challenges#3]
![why-waste-time-when-few-word-do-trick](https://user-images.githubusercontent.com/51025241/189052974-1f0b62ac-b2df-4243-9c07-116c0d0a7b5f.gif)

https://github.com/AnasHowlader/Programming-Challenges/blob/eee1be11555b862145670ea1fd2d9f79184fbe73/Brampton%20Manor%20Academy/Programming%20Challenge%202/Richter.py#L5-L21

```
 def tons_of_tnt(richter_value): 
     return float((magnitude(richter_value))/(4.184*10**9)) 
```

https://github.com/AnasHowlader/Programming-Challenges/blob/eee1be11555b862145670ea1fd2d9f79184fbe73/Brampton%20Manor%20Academy/Programming%20Challenge%202/Richter.py#L43-L47

```
values = [1,5,9.1,9.2,9.5]
for value in values:
    print(f"Energy released for a magnitude of {value}: {magnitude(value)/(4.184*10**9)} Joules")
```

**Comment by AnasHowlader** [comment]
@ecoppen Sir for challenge 13 im stuck on how to loop so it gives me the position numbers 1 -10

**Comment by ecoppen** [comment]
This is an issue for a different piece of code, if it’s done close it and make a new issue for the other code.
